version: "3.9"
services:
  web:
    build: ./client
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
  rails:
    build: ./server
    ports:
      - "3000:3000"
